import 'react-app-polyfill/ie11';
import * as React from 'react';
import * as ReactDOM from 'react-dom';
import { DataTable } from '../.';

// Define our columns
export const columns = [
  { label: 'First Name', field: 'firstName' },
  { label: 'Last Name', field: 'lastName' },
  { label: 'Start Date', field: 'startDate' },
  { label: 'Department', field: 'department' },
  { label: 'Date of Birth', field: 'birthDate' },
  { label: 'Street', field: 'streetLocation' },
  { label: 'City', field: 'cityLocation' },
  { label: 'State', field: 'stateLocation' },
  { label: 'Zip Code', field: 'zipCode' },
];

const data = [
  {
    firstName: 'Molli',
    lastName: 'Keeton',
    birthDate: '11/30/2001',
    startDate: '01/10/2021',
    streetLocation: '74 Walton Hill',
    cityLocation: 'Washington',
    stateLocation: 'DC',
    zipCode: '20099',
    department: 'marketing',
  },
  {
    firstName: 'Norris',
    lastName: 'Langridge',
    birthDate: '12/31/1997',
    startDate: '04/04/2020',
    streetLocation: '940 Bunker Hill Crossing',
    cityLocation: 'Indianapolis',
    stateLocation: 'IN',
    zipCode: '46207',
    department: 'marketing',
  },
  {
    firstName: 'Park',
    lastName: 'Coulter',
    birthDate: '01/06/1997',
    startDate: '12/24/2019',
    streetLocation: '78076 Loomis Circle',
    cityLocation: 'Philadelphia',
    stateLocation: 'PA',
    zipCode: '19141',
    department: 'human-resources',
  },
  {
    firstName: 'Gates',
    lastName: 'Stapleton',
    birthDate: '07/29/2002',
    startDate: '07/25/2015',
    streetLocation: '5 American Ash Terrace',
    cityLocation: 'Macon',
    stateLocation: 'GA',
    zipCode: '31217',
    department: 'sales',
  },
  {
    firstName: 'Sterling',
    lastName: 'Pieracci',
    birthDate: '02/11/2000',
    startDate: '03/12/2014',
    streetLocation: '43163 Sundown Crossing',
    cityLocation: 'Alexandria',
    stateLocation: 'LA',
    zipCode: '71307',
    department: 'engineering',
  },
  {
    firstName: 'Berny',
    lastName: 'Brakewell',
    birthDate: '09/29/2000',
    startDate: '05/31/2013',
    streetLocation: '87 Summer Ridge Avenue',
    cityLocation: 'Fresno',
    stateLocation: 'CA',
    zipCode: '93778',
    department: 'marketing',
  },
  {
    firstName: 'Roda',
    lastName: 'Alexsandrov',
    birthDate: '07/17/2001',
    startDate: '10/15/2015',
    streetLocation: '702 Northwestern Park',
    cityLocation: 'Portland',
    stateLocation: 'OR',
    zipCode: '97211',
    department: 'sales',
  },
  {
    firstName: 'Elia',
    lastName: 'Handforth',
    birthDate: '05/05/1998',
    startDate: '10/11/2019',
    streetLocation: '85545 Manitowish Place',
    cityLocation: 'Miami',
    stateLocation: 'FL',
    zipCode: '33147',
    department: 'marketing',
  },
  {
    firstName: 'Tull',
    lastName: 'Morewood',
    birthDate: '09/21/1995',
    startDate: '08/17/2021',
    streetLocation: '0 6th Parkway',
    cityLocation: 'Tucson',
    stateLocation: 'AZ',
    zipCode: '85748',
    department: 'legal',
  },
  {
    firstName: 'Myer',
    lastName: 'Ucceli',
    birthDate: '11/07/1996',
    startDate: '02/25/2019',
    streetLocation: '350 Bluejay Drive',
    cityLocation: 'Denver',
    stateLocation: 'CO',
    zipCode: '80243',
    department: 'sales',
  },
  {
    firstName: 'Darrelle',
    lastName: 'Dinsey',
    birthDate: '02/20/1998',
    startDate: '07/13/2014',
    streetLocation: '228 Del Sol Place',
    cityLocation: 'Jacksonville',
    stateLocation: 'FL',
    zipCode: '32215',
    department: 'human-resources',
  },
  {
    firstName: 'Gavin',
    lastName: 'Diack',
    birthDate: '11/04/1995',
    startDate: '05/26/2018',
    streetLocation: '47752 Weeping Birch Street',
    cityLocation: 'Syracuse',
    stateLocation: 'NY',
    zipCode: '13217',
    department: 'sales',
  },
  {
    firstName: 'Lidia',
    lastName: 'Polson',
    birthDate: '03/29/2000',
    startDate: '02/05/2017',
    streetLocation: '28224 Katie Circle',
    cityLocation: 'Charleston',
    stateLocation: 'WV',
    zipCode: '25305',
    department: 'legal',
  },
  {
    firstName: 'Baird',
    lastName: 'Stallebrass',
    birthDate: '03/15/1997',
    startDate: '04/23/2019',
    streetLocation: '17 Nancy Hill',
    cityLocation: 'Beaverton',
    stateLocation: 'OR',
    zipCode: '97075',
    department: 'engineering',
  },
  {
    firstName: 'Selle',
    lastName: 'Linskill',
    birthDate: '04/28/2002',
    startDate: '01/22/2017',
    streetLocation: '18 Hansons Hill',
    cityLocation: 'Denver',
    stateLocation: 'CO',
    zipCode: '80228',
    department: 'sales',
  },
  {
    firstName: 'Mead',
    lastName: 'Diemer',
    birthDate: '06/05/1997',
    startDate: '11/11/2013',
    streetLocation: '4 Melvin Alley',
    cityLocation: 'San Bernardino',
    stateLocation: 'CA',
    zipCode: '92424',
    department: 'legal',
  },
  {
    firstName: 'Larisa',
    lastName: 'Laurance',
    birthDate: '11/01/1997',
    startDate: '03/13/2017',
    streetLocation: '9980 Ridgeway Lane',
    cityLocation: 'Louisville',
    stateLocation: 'KY',
    zipCode: '40233',
    department: 'engineering',
  },
  {
    firstName: 'Jeniece',
    lastName: 'Mayoh',
    birthDate: '11/03/1998',
    startDate: '03/31/2018',
    streetLocation: '9 Gale Drive',
    cityLocation: 'Rochester',
    stateLocation: 'NY',
    zipCode: '14639',
    department: 'sales',
  },
  {
    firstName: 'Colene',
    lastName: 'Bricket',
    birthDate: '08/13/2002',
    startDate: '11/10/2017',
    streetLocation: '8 Pawling Lane',
    cityLocation: 'Boston',
    stateLocation: 'MA',
    zipCode: '02114',
    department: 'human-resources',
  },
  {
    firstName: 'Gus',
    lastName: 'Cottingham',
    birthDate: '12/04/1995',
    startDate: '12/23/2020',
    streetLocation: '4085 Norway Maple Lane',
    cityLocation: 'Houston',
    stateLocation: 'TX',
    zipCode: '77060',
    department: 'legal',
  },
];

const App = () => {
  return (
    <div>
      <DataTable columns={columns} rows={data} showingLength={[5, 10, 25]} />
    </div>
  );
};

ReactDOM.render(<App />, document.getElementById('root'));
